# This workflow will run tests using node and then publish a package to GitHub Packages when a tag is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and deploy release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm run build -- --prod --build-optimizer --optimization
      - name: rsync deployments
          uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzr --delete
            path: dist/
            remote_path: /var/www/pleagan/
            remote_host: pleagan.vg
            remote_user: pleagan
            remote_key: ${{ secrets.PLEAGAN_DEPLOY_KEY }}
